// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fast_pedigree_qc
List fast_pedigree_qc(CharacterVector ids, CharacterVector sires, CharacterVector dams);
RcppExport SEXP _pedivieweR_fast_pedigree_qc(SEXP idsSEXP, SEXP siresSEXP, SEXP damsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type ids(idsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type sires(siresSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type dams(damsSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_pedigree_qc(ids, sires, dams));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_pedivieweR_fast_pedigree_qc", (DL_FUNC) &_pedivieweR_fast_pedigree_qc, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_pedivieweR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
