# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fast_pedigree_qc <- function(ids, sires, dams) {
    .Call('_pedivieweR_fast_pedigree_qc', PACKAGE = 'pedivieweR', ids, sires, dams)
}

